server:
  port: 8080
#  ssl:
#    key-store: classpath:4059702_www.dududu.xyz.pfx
#    key-store-password: N5tIjWBG
#    key-store-type: PKCS12

#公司ssl
#
#  ssl:
#    key-store: classpath:4129810_www.lzjskt.com.pfx
#    key-store-password: KDCHn94n
#    key-store-type: PKCS12


spring:
  datasource:
    url: jdbc:mysql://47.95.213.208:3306/lz_applet?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: LZJX8888js.
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    cache: false
    mode: LEGACYHTML5
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

#redis
  redis:
    database: 0
    host: 182.92.122.144
    port: 6379
  servlet:
    multipart:
#     上传单个文件的大小
      max-file-size: 50MB
#     上传总文件的大小
      max-request-size: 200MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
#    打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml

#分页插件pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true


#fdfs配置
fdfs:
#  读取超时时间
  so-timeout: 15000
#  连接超时时间
  connect-timeout: 6000
  pool:
    jmx-enabled: false
#    缩略图
  thumb-image:
    width: 100
    height: 100
  tracker-list: 47.95.213.208:22122
#  跟踪器地址
#  tracker-list: 182.92.122.144:22122

#  tracker-list: 47.95.213.208:22122
#访问文件的ip地址
#fast.path: http://182.92.122.144/
fast.path: http://47.95.213.208/
#配置图片的style
phone.width: style='width:100%';
#文章头像
head.portrait: http://182.92.122.144/group1/M00/00/00/rBHBW17XS2iAdffwAATe4zUEBPI885.jpg

#// 设置单个文件大小
#spring.servlet.multipart.max-file-size= 50MB
#小程序AppID   wxcf4d62dbebe341ba

app:
  appId: wxcf4d62dbebe341ba
  secret: 7232308b676974b3e965ee46235beb06
  grant_type: authorization_code

